### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by Pie33000** [icc2115/sage#3]
Hi,
I would like to create a pull request to push my setup.py file to allow a simplified installation with pip.

Could you allow pull requests?

**Comment by icc2115** [comment]
Hi Pierrick - that's a good point, I've been meaning to upload a setup.py file. I just pushed a couple changes, you'll see that you can now install it locally by cloning and pip installing with setup.py, or you can just pip install using the package name `sage-importance` (since the package name `sage` was already taken).

**Comment by Pie33000** [comment]
Thank you Ian !
